

#ifndef __HUD.HUI_H__
#define __HUD.HUI_H__

// -- GENERATED BY MAYA

const int G_PROGRESSBAR = 1000;
const int TS_PAUSE = 1001;
const int TS_SCORE = 1002;
const int TS_BEST = 1003;
const int TS_DOWNLOADING = 1004;
const int TS_INSTRUCTIONS = 1005;
const int TD_CURRENTSCORE = 1006;
const int TD_BESTSCORE = 1007;
const int TD_CURRENTLEVEL = 1008;
const int TD_TIME = 1009;
const int TD_PERCENTAGE = 1010;
const int TD_CONSOLE1 = 1011;
const int TD_CONSOLE2 = 1012;
const int TD_CONSOLE3 = 1013;
const int TD_CONSOLE4 = 1014;
const int TD_CONSOLE5 = 1015;

#endif // __HUD.HUI_H__
